Update Color Scheme
catalyst-offgrid/catalyst-aip pull request #24
Opened 2020-11-17 10:14 UTC by AliceR

Centralize data viz colors in theme, making it easier to match colors on map and legend.

Also, changes the color of the bank layer and fixes the label.

2020-11-17 14:45 UTC, geohacker requested changes
![image](https://user-images.githubusercontent.com/371666/99404322-7e97ea00-2911-11eb-9d5a-cc0ccae78f66.png)

I think Bank, MFI and Sacco are still kind of close and hard to distinguish. Can we use some potentially very diverging colours? For example https://colorbrewer2.org/#type=diverging&scheme=RdGy&n=4

2020-11-18 17:26 UTC, AliceR commented
@geohacker I kept the financial services all with a shade of green, in order to be able to use other hues for the other categories (blues for health, pinkish for education, and the highlight orange for energy. Using a sequential color scheme within one of the categories takes too much color space away from the others. 

Also worth noting that using luminance within a hue creates a visual ranking. Might be desirable for health types (type 4 in lighter shade, less prominent?). Not sure if such ranking applies to the financial services - I tried to avoid it so far.

2020-11-18 17:27 UTC, AliceR commented
This is the current color palette:  https://coolors.co/304ca2-f98e08-6a9fb4-54a06f-679289-c8d6af-db93b0

2020-11-19 08:06 UTC, geohacker commented
@AliceR thank you. I took another stab at really diverging the colour scheme. They may not be great to look altogether but it makes it easy to distinguish which I think is that they want. 

![image](https://user-images.githubusercontent.com/371666/99638395-2cb7a700-2a6c-11eb-9b5e-6d806f68800d.png)
_everything_

![image](https://user-images.githubusercontent.com/371666/99638423-380ad280-2a6c-11eb-86f4-f6ac84fff6eb.png)
_just financial_

2020-11-19 08:43 UTC, AliceR commented
@geohacker I'll be honest, I don't like the random "confetti" look. But indeed, it does allow for the greatest differentiation between any given layer - Which seems to be considered more important than associative grouping.

Also, changing the colors should be easy enough to revisit by a maintainer later.
Can't approve my PR, so I'll leave it here: ✅

2020-11-19 09:31 UTC, geohacker commented
@AliceR definitely agree with you that the confetti look isn't aesthetically pleasing at all, but for now I'm inclined to just go with what allows for greater differentiation. Thank you!

2020-11-19 09:44 UTC, AliceR commented on src/components/Map.js
> +      // style: 'mapbox://styles/iandmuir/ckhom8rti07cy19pclrmewimq', // use this for high contrast roads
👍

2020-11-19 09:51 UTC, merged